[package]
name = "gray-cron"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
cron = { workspace = true }
gray-core = { workspace = true }
gray-plugin = { workspace = true }
async-trait = { workspace = true }
fs2 = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tempfile = { workspace = true }
